### PR TITLE
Make GitHub Dependabot keep existing GitHub Actions up to date (for free)

### PR DESCRIPTION
**Pull request by hartwork**
Will make GitHub Dependabot create pull requests for review (like the one at https://github.com/git-big-picture/git-big-picture/pull/46). It works great over there. What do you think?

### CODE REVIEW

**Comment by btel** [comment]
sounds great! how is it triggered?

**Comment by hartwork** [comment]
> sounds great! how is it triggered?

By merging, I'm not aware of any other way :man_shrugging: Would that be acceptable? You should get one or two pull requests with in a minute or two, that's how I have seen it happen in the past.

**Comment by btel** [comment]
i was asking, how the dependabot is triggered, once it's merged. but from the config I understand that's on weekly basis

**Comment by hartwork** [comment]
Okay, sorry. Weekly, yes.

**Comment by hartwork** [comment]
@btel I think this page — https://github.com/btel/svg_utils/network/dependencies — probably shows some first signs of Dependabot for you now, when you're logged in. Can you confirm?

**Comment by btel** [comment]
indeed

image

**Comment by hartwork** [comment]
I wonder why it hasn't created PRs to update from `checkout/releases@v2` to `v2.3.4` for https://github.com/btel/svg_utils/blob/master/.github/workflows/black.yml yet. I'm suspecting it's either because action `checkout/releases` abuses Git tag `v2` as a moving target (as do other actions) and the two are evaluated as equally new *or* they have some additional special handling :man_shrugging:

**Comment by hartwork** [comment]
Does the tab on Dependabot say anything about its first run or any other clues?

**Comment by btel** [comment]
this is what dependabot tab says:

image

i added you permissions to access the repo so you might be able to see the settings with your account

**Comment by hartwork** [comment]
Thanks! :pray: The page is not accessible to me though, not a big problem. I'm optimistic that the Dependabot config _will_ do updates at some point in the near future, e.g. because [run-tests.yml](https://github.com/btel/svg_utils/blob/master/.github/workflows/run-tests.yml) is using versions down to the patch level like `v2.3.4`, because I re-checked the file location and because I remember that Dependabot config errors would have been reported back to us.

I think to be consistent with versions of GitHub actions around here we could either make everything
- a) use the moving tag approach *or*
- b) use the explicit full version approach.

Approach (a) is going to be fewer pull requests and hence a little less "noise" but also when some action breaks our build in the future with (b) we'll know sooner — e.g. even if we don't do any own pull requests for weeks and nothing runs the CI — and we'll know in detail which version still worked and which version started breaking things: It will be obvious. To be fair, the problem that no CI may be run for weeks can also be addressed by adding a cron trigger to the existing actions.
Let's do what you feel comfortable with. How do you feel about these options?

**Comment by hartwork** [comment]
PS: Silly me: I should have accepted the invitation *before* checking that page :facepalm: :smiley: 
I can see it now and the config seems complete: It sees all three action files: It can be seen after a click on the ellipsis:

actions

[The update log](https://github.com/btel/svg_utils/network/updates/88652865) says `No update needed for` for each and all actions we use, I'm sort of hoping that that is meant for all occurrences. Else we'd have a Dependabot bug here and I will not "blame the compiler" before I'm sure, today :wink:

**Comment by btel** [comment]
I am fine with the full version approach. I like testing the full stack to the maximum 😄

**Pull request merged**
