### PR TITLE
Get width, height and viewBox back into SVG output (fixes #61)

### LINKED ISSUE #61: [0.3.3] Started producing SVG without width, height and viewBox
Hi @btel ,

due to my [rendering regression tests in xiangqi-setup](https://github.com/hartwork/xiangqi-setup/blob/master/test-for-rendering-regressions.sh) I noticed that things broke when [trying to upgrade to svgutils 0.3.3](https://github.com/hartwork/xiangqi-setup/pull/37). What happens is that the *width, height, and viewBox parameters are no longer included in the written SVG file*. Here's what that looks like in Inkscape: The dotted line is where the viewbox was with svgutils 0.3.2, the solid frame is where the new defacto viewbox is:

svgutils_0_3_3_viewbox

Here's a diff of before and after, with regard to the SVG output.
```diff
--- tests/actual-board-a4_blank_2cm_margin_BEFORE.svg   2021-02-10 11:22:04.300605915 +0100
+++ tests/actual-board-a4_blank_2cm_margin_AFTER.svg    2021-02-10 11:21:49.446494230 +0100
@@ -1,5 +1,5 @@
 <?xml version='1.0' encoding='ASCII' standalone='yes'?>
-<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="248.03149580999997px" viewBox="0 0 248.03149580999997 350.78740120838086" height="350.78740120838086px">
+<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
   <g>
     <g transform="translate(0, 0) scale(0.33333333299287476 0.33333333299287476) "><defs id="defs4"/>
   <sodipodi:namedview xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" id="base" pagecolor="#ffffff" bordercolor="#666666" borderopacity="1.0" inkscape:pageopacity="0.0" inkscape:pageshadow="2" inkscape:zoom="0.7" inkscape:cx="359.38222" inkscape:cy="512.51453" inkscape:document-units="px" inkscape:current-layer="layer1" showgrid="false" inkscape:window-width="1920" inkscape:window-height="1024" inkscape:window-x="0" inkscape:window-y="0" inkscape:window-maximized="1"/>
```

I have a feeling that #58 is causing this: `.width` and `.height` (with no underscores) are no longer set?
Is that a bug or a feature? How can I make svgutils 0.3.3 put width, height and viewBox into SVG output again?

Thanks and best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #61

### CODE REVIEW

**Comment by btel** [comment]
perfect! thanks!

**Comment by hartwork** [comment]
@btel would you be interested in a follow-up pull request dropping Travis and updating the image link in the readme to be GitHub Actions status? Do you have plans like that yourself?

**Comment by btel** [comment]
if you feel like doing it, please submit a PR. Thanks!

**Comment by hartwork** [comment]
> if you feel like doing it, please submit a PR. Thanks!

Alright, that would be #64 then :smiley:

**Pull request merged**
