### PR TITLE
Drop support for end-of-life versions of Python (fixes #66)

### LINKED ISSUE #66: Plans for dropping support for end-of-life Python 2.7 and 3.5?
Hi!

The oldest version of Python that has *not* [reached end of life](https://endoflife.date/python) as of today is Python 3.6. The svgutils code base currently supports 2.7 and 3.5 officially and in practice. I have seen people have vastly different opinions on which versions of Python should be supported by a project in 2021, before. So I would just like to hear what the current plan or approach about end-of-life Python is, and then see how and if I can help.
A benefit of dropping support for old versions, is that we could e.g. start using [f-strings](https://www.python.org/dev/peps/pep-0498/) and [type hints](https://docs.python.org/3/library/typing.html) in this code base if we wanted, in general.

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #66

### CODE REVIEW

**Comment by btel** [comment]
long live Python >3.5!

**Comment by btel** [comment]
btw can we use `python` instead of `python3` in the commands?

**Comment by hartwork** [comment]
> btw can we use `python` instead of `python3` in the commands?

Given recent https://github.com/git-big-picture/git-big-picture/issues/88 I'm not sure that's a good idea. What do you prefer about plain `python` or `python3` for a command?

**Comment by btel** [comment]
ok, sounds good!

**Review by btel — APPROVED** [review]

**Pull request merged**
