### PR TITLE
GitHub Actions: Start using explicit non-moving Git tags

### PR DESCRIPTION
**Pull request by hartwork**

### CODE REVIEW

**Review by btel — APPROVED** [review]
cool, thanks!

**Comment by btel** [comment]
you should be able to merge yourself, can you try?

**Comment by hartwork** [comment]
> you should be able to merge yourself, can you try?

The butt is gray for me still, because GitHub is waiting for two more 3.6 macOS checks to complete. With your approval given, I think I will be able to push that button sometime soon.

**Comment by btel** [comment]
ok, I will force merge it because the 3.6 check will be only available after #67 is merged

**Pull request merged**
