### PR TITLE
Add link to the documentation

### PR DESCRIPTION
**Pull request by CrazyPython**

### CODE REVIEW

**Comment by btel** [comment]
merged. Thanks a lot!

**Comment by CrazyPython** [comment]
Unrelated-- You might be interested in [svgmanip](https://github.com/CrazyPython/svgmanip), a tiny library with a more pythonic API and a smaller feature set targeting game developers.

**Comment by btel** [comment]
It's nice. Thanks for the link. If you file another PR, I can put the link on svgutils' readme page.

BTW Have you seen the `compose` API of svgutils (https://svgutils.readthedocs.io/en/latest/compose.html).
It may be more pythonic to your taste ;-)

**Comment by CrazyPython** [comment]
> If you file another PR, I can put the link on svgutils' readme page.
Thanks!

I did see `compose`. `svgutils` has a `.rotate()` that rotates about the center of the SVG and only one class- `Element`. It autodetects the height and width of images too.

**Pull request merged**
